name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch Secret from Azure Key Vault
        id: get_secret
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: 'wf-poc-test-kv'  
          secrets: 'maskedvariable'

      - name: Replace Secret in HTML
        run: |
          echo "Replacing with masked value"
          sed -i "s/SECRET_PLACEHOLDER/${{ steps.get_secret.outputs.maskedvariable }}/g" index.html

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"
          output_location: "/"
          action: "upload"
